# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/FinalProject/FinalProject.cache/wt [current_project]
set_property parent.project_path C:/FinalProject/FinalProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/FinalProject/FinalProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/FinalProject/FinalProject.srcs/sources_1/new/clock_divider.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/mode2.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/whoface.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/welcomeface.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/ssd_controller.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/spi_master.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/sadface.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/normalface.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/happyface.vhd
  C:/FinalProject/FinalProject.srcs/sources_1/new/finalproject.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FinalProject/FinalProject.srcs/constrs_1/new/finalproject.xdc
set_property used_in_implementation false [get_files C:/FinalProject/FinalProject.srcs/constrs_1/new/finalproject.xdc]


synth_design -top finalproject -part xc7z020clg484-1


write_checkpoint -force -noxdef finalproject.dcp

catch { report_utilization -file finalproject_utilization_synth.rpt -pb finalproject_utilization_synth.pb }
